default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: vervepress_development

test:
  <<: *default
  database: vervepress_test

production:
  <<: *default
  database: vervepress_production
