default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= DATABASE_USER %>
  password: <%= DATABASE_PASSWORD %>
  host: <%= DATABASE_HOST %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: vervepress_development

test:
  <<: *default
  database: vervepress_test

production:
  <<: *default
  database: vervepress_production
